### ISSUE TITLE
哥 只有UI没有实现代码吗 我就是想看代码嘛

### ISSUE THREAD

**Issue by the-ahnam** [MarleneJiang/Login_Register_Demo#1]
哥 只有UI没有实现代码吗 我就是想看代码嘛

**Comment by MarleneJiang** [comment]
抱歉，我只想说，这是用脚手架写的，如果无法理解，我也无能为力。
源码主要在src文件夹内。

**Comment by MarleneJiang** [comment]
> 哥 只有UI没有实现代码吗 我就是想看代码嘛

抱歉，我只想说，这是用脚手架写的，如果无法理解，我也无能为力。
源码主要在src文件夹内。
